apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.Name }}"
  labels:
    app: "{{ .Values.Name }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.Name }}"
  ports:
    - protocol: TCP
      name: http
      port: 4000
      targetPort: 80