apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.name }}"
  ports:
    - protocol: TCP
      name: http
      port: 4000
      targetPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.nameBackend }}"
  labels:
    app: "{{ .Values.nameBackend }}"
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.nameBackend }}"
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: {{ .Values.nameBackend }}-ingress
#   labels:
#     app: {{ .Values.nameBackend }}
# spec:
#   rules:
#   - host: 172.22.145.148
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: {{ .Values.nameBackend }}
#           servicePort: 5000